DROP TABLE T_SIP_IMPLANTACAO CASCADE CONSTRAINTS;
DROP TABLE T_SIP_PROJETO CASCADE CONSTRAINTS;
DROP TABLE T_SIP_DEPENDENTE CASCADE CONSTRAINTS;
DROP TABLE T_SIP_FUNCIONARIO CASCADE CONSTRAINTS;
DROP TABLE T_SIP_DEPTO CASCADE CONSTRAINTS;

--CASCADE CONSTRAINTS -> ELIMINA O RELACIONAMENTO

--------DEPARTAMENTO--------
CREATE TABLE T_SIP_DEPTO
(
	CD_DEPTO	NUMBER (3)	NOT NULL,
	NM_DEPTO	VARCHAR(30)	NOT NULL,
	SG_DEPTO	CHAR(3)	NOT NULL
);

--CONSTRAINT CHAVE PRIMARIA
	ALTER TABLE T_SIP_DEPTO
ADD CONSTRAINT PK_SIP_DEPTO
	PRIMARY KEY(CD_DEPTO);

--CONSTRAINT UNIQUE
	ALTER TABLE T_SIP_DEPTO
ADD CONSTRAINT UN_SIP_DEPTO_NOME
	UNIQUE(NM_DEPTO);




--------FUNCIONARIO--------
CREATE TABLE T_SIP_FUNCIONARIO
(
	NR_MATRICULA		NUMBER(5)		NOT NULL,
	CD_DEPTO			NUMBER(3)		NOT NULL,
	NM_FUNCIONARIO		VARCHAR2(50)	NOT NULL,
	DT_NASCIMENTO		DATE			NOT NULL,
	DT_ADMISSAO			DATE        	NOT NULL,
	DS_ENDERECO			VARCHAR2(100)	NOT NULL,
	VL_SALARIO_MENSAL	NUMBER(7,2)		NOT NULL
);

--CONSTRAINT CHAVE PRIMARIA
	ALTER TABLE T_SIP_FUNCIONARIO
ADD CONSTRAINT PK_SIP_FUNCIONARIO
	PRIMARY KEY(NR_MATRICULA);

--CONSTRAINT CHECK
	ALTER TABLE T_SIP_FUNCIONARIO
ADD CONSTRAINT CK_SIP_FUNC_SALARIO
	CHECK (VL_SALARIO_MENSAL >= 1045);




--------DEPENDENTE--------
CREATE TABLE T_SIP_DEPENDENTE
(
	NR_MATRICULA		NUMBER(5)		NOT NULL,
	CD_DEPENDENTE		NUMBER(2)		NOT NULL,
	NM_DEPENDENTE		VARCHAR2(50)	NOT NULL,
	DT_NASCIMENTO		DATE            NOT NULL
);

--CONSTRAINT CHAVE PRIMARIA
	ALTER TABLE T_SIP_DEPENDENTE
ADD CONSTRAINT PK_SIP_DEPENDENTE
	PRIMARY KEY(NR_MATRICULA,CD_DEPENDENTE);
-- CHAVE PRIMARIA COMPOSTA (FRACA) => CHAVE ESTRANGEIRA + CAMPO DA PROPRIA ENTIDADE




--------IMPLANTACAO--------
CREATE TABLE T_SIP_IMPLANTACAO
(
	CD_PROJETO			NUMBER(5)		NOT NULL,
	CD_IMPLANTACAO		NUMBER(3)		NOT NULL,
	NR_MATRICULA		NUMBER(5)		NOT NULL,
	DT_ENTRADA			DATE            NOT NULL,
	DT_SAIDA			DATE			NULL
);

--CONSTRAINT CHAVE PRIMARIA
	ALTER TABLE T_SIP_IMPLANTACAO
ADD CONSTRAINT PK_SIP_IMPLANTACAO
	PRIMARY KEY(CD_PROJETO,CD_IMPLANTACAO);
--CHAVE PRIMARIA COMPOSTA (ASSOCIATIVA) => PELAS DUAS CHAVES ESTRANGEIRAS

--CONSTRAINT CHECK
	ALTER TABLE T_SIP_IMPLANTACAO
ADD CONSTRAINT CK_SIP_IMPLANTACAO_DATE
	CHECK(DT_SAIDA > DT_ENTRADA);




--------PROJETO--------
CREATE TABLE T_SIP_PROJETO
(
	CD_PROJETO		NUMBER(5)		NOT NULL,
	NM_PROJETO		VARCHAR2(40)	NOT NULL,
	DT_INICIO		DATE            NOT NULL,
	DT_TERMINO		DATE  			NULL
);
--QUANDO O CMAPO É OPCIONAL NÃO PRECISA INFORMAR O NULL (DEFAULT)

--CONSTRAINT CHAVE PRIMARIA
	ALTER TABLE T_SIP_PROJETO
ADD CONSTRAINT PK_SIP_PROJETO
	PRIMARY KEY(CD_PROJETO);

--CONSTRAINT UNIQUE
	ALTER TABLE T_SIP_PROJETO
ADD CONSTRAINT UN_SIP_PROJETO_NOME
	UNIQUE(NM_PROJETO);

--CONSTRAINT CHECK
	ALTER TABLE T_SIP_PROJETO
ADD CONSTRAINT CK_SIP_PROJETO_DATA
	CHECK(DT_TERMINO > DT_INICIO);




--------RELACIONAMENTOS--------
-- RELACIONAMENTO ENTRE FUNCIONARIO (DESTINO) E DEPARTAMENTO (ORIGEM)
ALTER TABLE T_SIP_FUNCIONARIO
ADD CONSTRAINT FK_SIP_FUNC_DEPTO
	FOREIGN KEY (CD_DEPTO)
	REFERENCES T_SIP_DEPTO (CD_DEPTO);

--RELACIONAMENTO ENTRE DEPENDENTE (DESTINO) E FUNCIONARIO (ORIGEM)
ALTER TABLE T_SIP_DEPENDENTE
ADD CONSTRAINT FK_SIP_DEPENDENTE_FUNC
	FOREIGN KEY (NR_MATRICULA)
	REFERENCES T_SIP_FUNCIONARIO (NR_MATRICULA);

--RELACIONAMENTO ENTRE IMPLANTAÇÃO (DESTINO) E FUNCIONARIO (ORIGEM)
ALTER TABLE T_SIP_IMPLANTACAO
ADD CONSTRAINT FK_SIP_IMPLANT_FUNC
	FOREIGN KEY (NR_MATRICULA)
	REFERENCES T_SIP_FUNCIONARIO (NR_MATRICULA);

--RELACIONAMENTO ENTRE IMPLANTAÇÃO (DESTINO) E PROJETO (ORIGEM)
ALTER TABLE T_SIP_IMPLANTACAO
ADD CONSTRAINT FK_SIP_IMPLANT_PROJETO
	FOREIGN KEY (CD_PROJETO)
	REFERENCES T_SIP_PROJETO (CD_PROJETO);